name: docs
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  desktop:
    path: ../desktop
    
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  assets:
    - assets/GitHub-Mark-120px-plus.png
    - assets/GitHub-Mark-Light-120px-plus.png
    
    - assets/cats/pexels-akbar-nemati-5622738.jpg
    - assets/cats/pexels-aleksandr-nadyojin-4492149.jpg
    - assets/cats/pexels-anete-lusina-4790622.jpg
    - assets/cats/pexels-bianca-marolla-3030635.jpg
    - assets/cats/pexels-christopher-schruff-720684.jpg
    - assets/cats/pexels-danielle-daniel-479009.jpg
    - assets/cats/pexels-david-savochka-192384.jpg
    - assets/cats/pexels-dương-nhân-2817405.jpg
    - assets/cats/pexels-emily-geibel-3772262.jpg
    - assets/cats/pexels-emir-kaan-okutan-2255565.jpg
    - assets/cats/pexels-engin-akyurt-1571724.jpg
    - assets/cats/pexels-evg-culture-1416792.jpg
    - assets/cats/pexels-faris-subriun-4391733.jpg
    - assets/cats/pexels-flickr-156321.jpg
    - assets/cats/pexels-fotografierende-3127729.jpg
    - assets/cats/pexels-francesco-ungaro-96428.jpg
    - assets/cats/pexels-halil-i̇brahim-çeti̇n-1754986.jpg
    - assets/cats/pexels-hugo-zoccal-fernandes-laguna-1299518.jpg
    - assets/cats/pexels-jan-kopřiva-5800065.jpg
    - assets/cats/pexels-josé-andrés-pacheco-cortes-5456616.jpg
    - assets/cats/pexels-leonardo-de-oliveira-1770918.jpg
    - assets/cats/pexels-levent-simsek-4411430.jpg
    - assets/cats/pexels-luan-oosthuizen-1784289.jpg
    - assets/cats/pexels-mark-burnett-731553.jpg
    - assets/cats/pexels-mati-mango-4734723.jpg
    - assets/cats/pexels-matteo-petralli-1828875.jpg
    - assets/cats/pexels-matthias-oben-5281143.jpg
    - assets/cats/pexels-mustafa-ezz-979503.jpg
    - assets/cats/pexels-peng-louis-1643457.jpg
    - assets/cats/pexels-peng-louis-1653357.jpg
    - assets/cats/pexels-piers-olphin-5044690.jpg
    - assets/cats/pexels-pixabay-45170.jpg
    - assets/cats/pexels-pixabay-45201.jpg
    - assets/cats/pexels-pixabay-104827.jpg
    - assets/cats/pexels-pixabay-160755.jpg
    - assets/cats/pexels-pixabay-271611.jpg
    - assets/cats/pexels-tamba-budiarsana-979247.jpg
    - assets/cats/pexels-tomas-ryant-2693561.jpg
    - assets/cats/pexels-utku-koylu-2611939.jpg
    - assets/cats/pexels-xue-guangjian-1687831.jpg
    - assets/cats/pexels-zhang-kaiyv-4858815.jpg
    - assets/cats/pexels-александар-цветановић-1440406.jpg

    - assets/cats_small/pexels-akbar-nemati-5622738.jpg
    - assets/cats_small/pexels-aleksandr-nadyojin-4492149.jpg
    - assets/cats_small/pexels-anete-lusina-4790622.jpg
    - assets/cats_small/pexels-bianca-marolla-3030635.jpg
    - assets/cats_small/pexels-christopher-schruff-720684.jpg
    - assets/cats_small/pexels-danielle-daniel-479009.jpg
    - assets/cats_small/pexels-david-savochka-192384.jpg
    - assets/cats_small/pexels-dương-nhân-2817405.jpg
    - assets/cats_small/pexels-emily-geibel-3772262.jpg
    - assets/cats_small/pexels-emir-kaan-okutan-2255565.jpg
    - assets/cats_small/pexels-engin-akyurt-1571724.jpg
    - assets/cats_small/pexels-evg-culture-1416792.jpg
    - assets/cats_small/pexels-faris-subriun-4391733.jpg
    - assets/cats_small/pexels-flickr-156321.jpg
    - assets/cats_small/pexels-fotografierende-3127729.jpg
    - assets/cats_small/pexels-francesco-ungaro-96428.jpg
    - assets/cats_small/pexels-halil-i̇brahim-çeti̇n-1754986.jpg
    - assets/cats_small/pexels-hugo-zoccal-fernandes-laguna-1299518.jpg
    - assets/cats_small/pexels-jan-kopřiva-5800065.jpg
    - assets/cats_small/pexels-josé-andrés-pacheco-cortes-5456616.jpg
    - assets/cats_small/pexels-leonardo-de-oliveira-1770918.jpg
    - assets/cats_small/pexels-levent-simsek-4411430.jpg
    - assets/cats_small/pexels-luan-oosthuizen-1784289.jpg
    - assets/cats_small/pexels-mark-burnett-731553.jpg
    - assets/cats_small/pexels-mati-mango-4734723.jpg
    - assets/cats_small/pexels-matteo-petralli-1828875.jpg
    - assets/cats_small/pexels-matthias-oben-5281143.jpg
    - assets/cats_small/pexels-mustafa-ezz-979503.jpg
    - assets/cats_small/pexels-peng-louis-1643457.jpg
    - assets/cats_small/pexels-peng-louis-1653357.jpg
    - assets/cats_small/pexels-piers-olphin-5044690.jpg
    - assets/cats_small/pexels-pixabay-45170.jpg
    - assets/cats_small/pexels-pixabay-45201.jpg
    - assets/cats_small/pexels-pixabay-104827.jpg
    - assets/cats_small/pexels-pixabay-160755.jpg
    - assets/cats_small/pexels-pixabay-271611.jpg
    - assets/cats_small/pexels-tamba-budiarsana-979247.jpg
    - assets/cats_small/pexels-tomas-ryant-2693561.jpg
    - assets/cats_small/pexels-utku-koylu-2611939.jpg
    - assets/cats_small/pexels-xue-guangjian-1687831.jpg
    - assets/cats_small/pexels-zhang-kaiyv-4858815.jpg
    - assets/cats_small/pexels-александар-цветановић-1440406.jpg

  fonts:
    - family: IBM Plex Mono
      fonts:
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-ExtraLightItalic.ttf
          style: italic
          weight: 200          
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-SemiBoldItalic.ttf
          style: normal
          weight: 600
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-SemiBoldItalic.ttf
          style: italic
          weight: 600  
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/IBM_Plex_Mono/IBMPlexMono-BoldItalic.ttf
          style: italic
          weight: 700

    - family: IBM Plex Sans
      fonts:
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-ExtraLightItalic.ttf
          style: italic
          weight: 200          
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-SemiBoldItalic.ttf
          style: normal
          weight: 600
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-SemiBoldItalic.ttf
          style: italic
          weight: 600  
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-BoldItalic.ttf
          style: italic
          weight: 700

    - family: IBM Plex Serif
      fonts:
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-ExtraLightItalic.ttf
          style: italic
          weight: 200          
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-SemiBoldItalic.ttf
          style: normal
          weight: 600
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-SemiBoldItalic.ttf
          style: italic
          weight: 600  
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-BoldItalic.ttf
          style: italic
          weight: 700

    - family: mode
      fonts:
        - asset: fonts/mode.ttf
        
    - family: SharpMaterialIcons
      fonts:
        - asset: fonts/sharp_material_icons.ttf