name: desktop
description: Flutter design standard for desktop.
repository: https://github.com/adrianos42/desktop
homepage: https://adrianos42.github.io/native_idl/desktop
version: 0.1.1-2.12.0-0

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: IBMPlexSerif
      fonts:
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Light.ttf
          weight: 300
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Regular.ttf
          weight: 400
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Medium.ttf
          weight: 500
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-SemiBold.ttf
          weight: 600  
        - asset: fonts/IBM_Plex_Serif/IBMPlexSerif-Bold.ttf
          weight: 700
        
    - family: IBMPlexSans
      fonts:
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Light.ttf
          weight: 300
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-SemiBold.ttf
          weight: 600  
        - asset: fonts/IBM_Plex_Sans/IBMPlexSans-Bold.ttf
          weight: 700


    - family: SharpMaterialIcons
      fonts:
        - asset: fonts/sharp_material_icons.ttf